import {
  BookOpen,
  Drama,
  Layers,
  Sparkles,
  TrendingUp,
  Users,
} from "lucide-react";
import {
  BlueprintSection,
  BlueprintText,
} from "@/components/blueprint/blueprint-section";
import type { StoryBlueprint } from "@/lib/blueprint/types";

interface BlueprintDisplayProps {
  blueprint: StoryBlueprint;
}

export function BlueprintDisplay({ blueprint }: BlueprintDisplayProps) {
  return (
    <div className="space-y-5 animate-fade-in">
      <BlueprintSection
        title="Story Summary"
        icon={<BookOpen className="h-4 w-4" />}
      >
        <BlueprintText>{blueprint.summary}</BlueprintText>
      </BlueprintSection>

      <BlueprintSection
        title="Main Conflict"
        icon={<Drama className="h-4 w-4" />}
      >
        <BlueprintText>{blueprint.conflict}</BlueprintText>
      </BlueprintSection>

      <BlueprintSection
        title="Character Arc"
        icon={<TrendingUp className="h-4 w-4" />}
      >
        <div className="space-y-4">
          {(
            [
              ["Beginning", blueprint.characterArc.beginning],
              ["Middle", blueprint.characterArc.middle],
              ["Ending", blueprint.characterArc.ending],
            ] as const
          ).map(([phase, text]) => (
            <div
              key={phase}
              className="rounded-xl border border-white/5 bg-white/[0.02] p-4"
            >
              <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-purple-light">
                {phase}
              </p>
              <BlueprintText>{text}</BlueprintText>
            </div>
          ))}
        </div>
      </BlueprintSection>

      <BlueprintSection
        title="Supporting Characters"
        icon={<Users className="h-4 w-4" />}
      >
        <div className="grid gap-3 sm:grid-cols-2">
          {blueprint.supportingCharacters.map((character) => (
            <div
              key={character.name}
              className="rounded-xl border border-white/5 bg-white/[0.02] p-4"
            >
              <p className="font-semibold text-foreground">{character.name}</p>
              <p className="mt-1 text-xs font-medium text-blue-light">
                {character.role}
              </p>
              <p className="mt-2 text-sm leading-relaxed text-muted">
                {character.personality}
              </p>
            </div>
          ))}
        </div>
      </BlueprintSection>

      <BlueprintSection
        title="Chapter Outline"
        icon={<Layers className="h-4 w-4" />}
      >
        <div className="space-y-3">
          {blueprint.chapterOutline.map((chapter) => (
            <div
              key={chapter.chapterNumber}
              className="flex gap-4 rounded-xl border border-white/5 bg-white/[0.02] p-4 transition-colors hover:border-white/10"
            >
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-purple/20 to-blue/20 text-sm font-bold text-purple-light">
                {chapter.chapterNumber}
              </div>
              <div className="min-w-0 flex-1">
                <p className="font-medium text-foreground">{chapter.title}</p>
                <p className="mt-1 text-sm leading-relaxed text-muted">
                  {chapter.summary}
                </p>
              </div>
            </div>
          ))}
        </div>
      </BlueprintSection>

      <div className="flex items-center gap-2 text-xs text-muted">
        <Sparkles className="h-3.5 w-3.5 text-purple-light" />
        <span>Generated by AI Story Architect</span>
      </div>
    </div>
  );
}
